### PR TITLE
add support for mips64el

### PR DESCRIPTION
**Pull request by wanghuaiqing2010**
Signed-off-by: wanghuaiqing <wanghuaiqing@loongson.cn>

### CODE REVIEW

**Comment by wanghuaiqing2010** [comment]
The code I submit will not affect the code of other architectures.
I don't know why all checks have failed.
Please help me

**Comment by wanghuaiqing2010** [comment]
@Tianon could you help me?

**Comment by tianon** [comment]
It's failing because the binary has to be checked in, but I'd frankly rather resolve the (serious) implications of what we've discovered in #62 before we add more architectures, because it could have a pretty major effect on how we approach supporting more architectures (ie, we might end up having to have builders for each targeted architecture, which would complicate this as we've been discussing), so I don't want to commit to supporting more architectures until we're sure we can do so in whatever new build method we come up with.

**Comment by tianon** [comment]
Also, to be clear, while looking at solutions for #62 I *am* considering whether `mips64le` can be supported as well, I just don't want to commit to it completely ahead of a solution to that.

I have had roughly this same change sitting in my local copy of this repo for a minute trying to decide how to move forward on this, and my latest test with `musl` was successful against this same `mips64le` cross-compiler FWIW.

**Comment by wanghuaiqing2010** [comment]
@tianon Thanks for your reply. 
I understand what you mean.

**Pull request closed without merging**
