### PR TITLE
feat: add support for creating multi-arch images using buildx

### PR DESCRIPTION
**Pull request by HarikrishnanBalagopal**
https://docs.docker.com/build/building/multi-platform/

### CODE REVIEW

**Comment by yosifkit** [comment]
Thanks for the contribution.

The images here are not built all at once since the source and binary rarely change. We have a [Dockerfile.build](https://github.com/docker-library/hello-world/blob/415840e3fe9706ea8657e645d6eaaa674924dadd/Dockerfile.build) to create the binaries via cross compilation (rather than emulation that buildx would likely use). The small binaries are committed to the git repo (each folder contains the binary for the respective architecture). The `Makefile` is only run from within that builder container. We then send the relevant commit to official images (like [this PR](https://github.com/docker-library/official-images/pull/12072)), and each `FROM scratch` image is built on their respective architecture (like [arm64v8](https://github.com/docker-library/hello-world/blob/415840e3fe9706ea8657e645d6eaaa674924dadd/arm64v8/hello-world/Dockerfile)).

**Comment by HarikrishnanBalagopal** [comment]
> Thanks for the contribution.
> 
> The images here are not built all at once since the source and binary rarely change. We have a [Dockerfile.build](https://github.com/docker-library/hello-world/blob/415840e3fe9706ea8657e645d6eaaa674924dadd/Dockerfile.build) to create the binaries via cross compilation (rather than emulation that buildx would likely use). The small binaries are committed to the git repo (each folder contains the binary for the respective architecture). The `Makefile` is only run from within that builder container. We then send the relevant commit to official images (like [this PR](https://github.com/docker-library/official-images/pull/12072)), and each `FROM scratch` image is built on their respective architecture (like [arm64v8](https://github.com/docker-library/hello-world/blob/415840e3fe9706ea8657e645d6eaaa674924dadd/arm64v8/hello-world/Dockerfile)).

Thanks for the feedback! Is there a reason you don't use the official `gcc` image during building? https://github.com/docker-library/hello-world/blob/415840e3fe9706ea8657e645d6eaaa674924dadd/Dockerfile.build#L11

**Comment by yosifkit** [comment]
> Is there a reason you don't use the official `gcc` image during building?

Since the simple "Hello World" binaries are all cross built on one architecture, the Debian packages are user friendly for that (`gcc-aarch64-linux-gnu`, etc). The `gcc` image is mostly meant for compiling on a native architecture and doesn't include cross compilation.

**Comment by tianon** [comment]
The `gcc` image is also a very "upstream" GCC experience, and as such isn't typically the most user friendly image (most dependencies would need to be downloaded and installed manually instead of via packages, for example).

**Pull request closed without merging**
