### PR TITLE
Use new microsoft/nanoserver tags (sac2016)

### PR DESCRIPTION
**Pull request by tianon**
See https://hub.docker.com/r/microsoft/nanoserver/ (:1709 vs :sac2016)

### CODE REVIEW

**Comment by tianon** [comment]
(I've already updated our builder to include `nanoserver-1709` and `nanoserver-sac2016` as additional constraints, in addition to `windowsservercore-1709` and `windowsservercore-ltsc2016`)

**Comment by tianon** [comment]
```diff
$ diff -u <(bashbrew cat hello-world) <(bashbrew cat <(./generate-stackbrew-library.sh))
--- /dev/fd/63	2017-11-20 10:57:05.456567972 -0800
+++ /dev/fd/62	2017-11-20 10:57:05.456567972 -0800
@@ -1,6 +1,6 @@
 Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon), Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
 GitRepo: https://github.com/docker-library/hello-world.git
-GitCommit: b9c8214f529b04e37683fddba4a4244308f046e8
+GitCommit: 369e5a42372140f46e5a6b09e0b17ccfe8780521
 
 Tags: linux
 SharedTags: latest
@@ -20,16 +20,16 @@
 s390x-Directory: s390x/hello-world
 s390x-GitCommit: c83a065a24e94e635ddd518c2a3cffc91accf30d
 
-Tags: nanoserver
-SharedTags: latest
+Tags: nanoserver-sac2016
+SharedTags: nanoserver, latest
 Architectures: windows-amd64
-windows-amd64-Directory: amd64/hello-world/nanoserver
-windows-amd64-GitCommit: c83a065a24e94e635ddd518c2a3cffc91accf30d
-Constraints: nanoserver
+windows-amd64-Directory: amd64/hello-world/nanoserver-sac2016
+windows-amd64-GitCommit: 369e5a42372140f46e5a6b09e0b17ccfe8780521
+Constraints: nanoserver-sac2016
 
-Tags: nanoserver1709
-SharedTags: latest
+Tags: nanoserver-1709
+SharedTags: nanoserver, latest
 Architectures: windows-amd64
-windows-amd64-Directory: amd64/hello-world/nanoserver1709
-windows-amd64-GitCommit: c83a065a24e94e635ddd518c2a3cffc91accf30d
-Constraints: nanoserver1709
+windows-amd64-Directory: amd64/hello-world/nanoserver-1709
+windows-amd64-GitCommit: 369e5a42372140f46e5a6b09e0b17ccfe8780521
+Constraints: nanoserver-1709
```

**Comment by tianon** [comment]
Thoughts?

**Comment by yosifkit** [comment]
Since I am unsure if Microsoft would be ok with number 3 or 4, then it seems number 2 is our least ugly option.
1. `hello-world:nanoserversac2016`
1. `hello-world:nanoserver-sac2016`
1. `hello-world:nanoserver-2016`
   - `windowsservercore` could have the same suffix on other images :stuck_out_tongue: 
1. `hello-world:nanoserver-ltsc2016`
   - use the tag from `windowsservercore`?

**Comment by tianon** [comment]
Maybe @taylorb-microsoft would be willing to comment on our variant naming, since we'll be replicating this outwards to other images (see https://github.com/docker-library/hello-world/pull/41#issuecomment-345793212 through @yosifkit's comment). :pray:

**Comment by taylorb-microsoft** [comment]
A bit of the history/sob story.  We now version/name windows server releases with year/month (1709, 1803, 1809 etc...) so we decided that consistent with other images the "image version - base image naming" made since (i.e. 2.0-dotnet-xyz)...  which is fine.  

Then the wrinkles.  First we have Windows Server 2016, which was before this version branding started and for legal/branding considerations we can't go back and make one up so we said fine we'll call out sac2016 to make sure it's clear what it is at least (even though sac means nothing to anyone outside of Windows unless you read the description but at least it begs the question), that having letters in it meant we needed a delimiter thus -.

One important note - Nano server has not, yet, had an LTSC release.

**Comment by taylorb-microsoft** [comment]
this is what we're using for other Microsoft images btw: "_<imageversion>_-_<imagename>_-nanoserver-1709".

**Comment by tianon** [comment]
Thanks so much for both the history and the added perspective @taylorb-microsoft :heart: :heart:

Given that, I think we'll go with the `nanoserver-XXX` (@yosifkit's option 2) which matches other Microsoft images too. :+1:

**Comment by tianon** [comment]
PRs for docker-library-maintained images open ^^

**Pull request merged**
