### PR TITLE
Update link and shorter example

### PR DESCRIPTION
**Pull request by thaJeztah**
the link to the userguide was updated, so updating
it in the hello-world image to save a redirect.

also removed "bash" from the example, because it's
the default for the ubuntu image.

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tianon I wasn't sure if you wanted to keep the `bash` in the ubuntu example (or even change it to `docker run -it alpine sh`), so happy to hear :-)

**Comment by tianon** [comment]
Ah nice!  I do like keeping `bash` in here since it helps reinforce the concept of `docker run <image> <command>` really early on without having to have users think about default commands. :+1:

(and I'm also a fan of leaving this on `ubuntu` specifically because it's a name most users have heard before, so it's a good "second intro image" -- otherwise I would've switched it to `debian` ages ago :see_no_evil:)

**Comment by thaJeztah** [comment]
Yes, I also thought about that; having them run `ubuntu` once, warms up their image cache for a better experience in further examples. Let me change that line back

**Comment by thaJeztah** [comment]
updated 👍

**Comment by tianon** [comment]
LGTM :+1:

Thanks! :smile:

**Pull request merged**
