### PR TITLE
Switch to C officially, especially for multi-architecture compatibility

### LINKED ISSUE #7: ARM compatible version of this hello-world image?
When running the `make test-integration-cli` on ARM this hello-world Docker image is used from the Dockerhub.

It fails with the following error:
```
Docker daemon 2.048 kB\rSending build context to Docker daemon 2.048 kB\r\r\nStep 1 : FROM hello-world:frozen\n ---> 91c95931e552\nStep 2 : RUN /hello\n ---> Running in 0b36a68d0e07\n\x1b[91mexec format error\n\x1b[0m[8] System error: exec format error\n"
```

It seems that the binary needs to be made specifically for the armhf architecture.

Made a first draft of an armhf compatible hello-world image here: https://github.com/hypriot/armhf-hello-world

The question is, if this should be merged with this repo or if it should remain separate?

### PR DESCRIPTION
**Pull request by tianon**
Fixes #7
Closes #9 (carried)

### CODE REVIEW

**Comment by ncopa** [comment]
Protip: link static with musl using `musl-dev`. Will reduce size significantly.

**Comment by tianon** [comment]
Oh, that is available in Debian! (https://packages.debian.org/sid/musl-dev)

I'll play, thanks! :smile:

**Comment by tianon** [comment]
It appears not to cover `s390x`, but it does have decent coverage for other arches, so I'll see what I can come up with.

**Comment by tianon** [comment]
Before: (`glibc`)
```console
+ ls -l hello-seattle/hello hello-world/hello hola-mundo/hello
-rwxr-xr-x 1 root root 1864 Jun 29 23:37 hello-seattle/hello
-rwxr-xr-x 1 root root 1848 Jun 29 23:37 hello-world/hello
-rwxr-xr-x 1 root root 1864 Jun 29 23:37 hola-mundo/hello
```

After: (`musl`)
```console
+ ls -l hello-seattle/hello hello-world/hello hola-mundo/hello
-rwxr-xr-x 1 root root 1760 Jun 30 17:13 hello-seattle/hello
-rwxr-xr-x 1 root root 1736 Jun 30 17:13 hello-world/hello
-rwxr-xr-x 1 root root 1760 Jun 30 17:13 hola-mundo/hello
```

Changes:
```diff
diff --git a/Dockerfile.build b/Dockerfile.build
index ed3de7c..b81d465 100644
--- a/Dockerfile.build
+++ b/Dockerfile.build
@@ -1,10 +1,15 @@
 # explicitly use Debian for maximum cross-architecture compatibility
 FROM debian:jessie
 
-RUN apt-get update && apt-get install -y --no-install-recommends \
-		gcc \
-		libc6-dev \
-		make \
+RUN set -ex \
+	&& apt-get update \
+# s390x does not have "musl-tools" or "musl-dev", so we need a fallback
+	&& if apt-cache show musl-tools > /dev/null 2>&1; then \
+		gcc='musl-tools musl-dev'; \
+	else \
+		gcc='gcc libc6-dev'; \
+	fi \
+	&& apt-get install -y --no-install-recommends make $gcc \
 	&& rm -rf /var/lib/apt/lists/*
 
 WORKDIR /usr/src/hello
diff --git a/Makefile b/Makefile
index d0b0b63..35c0fb4 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,8 @@
+SHELL := /bin/bash
+
 C_TARGETS := $(addsuffix hello, $(wildcard */))
 
-CC := gcc
+CC := $(shell command -v musl-gcc &> /dev/null && echo musl-gcc || echo gcc)
 CFLAGS := -static -Os -nostartfiles -fno-asynchronous-unwind-tables
 
 .PHONY: all
diff --git a/hello-seattle/hello b/hello-seattle/hello
index f7ef94c..7e1d530 100755
Binary files a/hello-seattle/hello and b/hello-seattle/hello differ
diff --git a/hello-world/hello b/hello-world/hello
index 7f3f7f8..9f6f7da 100755
Binary files a/hello-world/hello and b/hello-world/hello differ
diff --git a/hola-mundo/hello b/hola-mundo/hello
index 4d6496d..6a8804c 100755
Binary files a/hola-mundo/hello and b/hola-mundo/hello differ
```

**Comment by yosifkit** [comment]
LGTM, I don't think ~100 bytes warrants the extra complexity.

**Pull request merged**
