### PR TITLE
Add "Dockerfile.build" for building

### PR DESCRIPTION
**Pull request by tianon**
As mentioned by @thaJeztah in https://github.com/docker-library/hello-world/pull/5#issuecomment-111300414. :+1:

### CODE REVIEW

**Comment by thaJeztah** [comment]
Oh, thanks! :heart:

**Comment by tianon** [comment]
It was a good idea -- didn't want it to get lost! :+1: :heart:

**Comment by yosifkit** [comment]
LGTM

**Comment by thaJeztah** [comment]
Oh! tested it, and works like a charm :)

**Comment by tianon** [comment]
:metal:

**Pull request merged**
