### PR TITLE
Add SharedTags (so that "docker run hello-world" can work on Windows too!)

### PR DESCRIPTION
**Pull request by tianon**
cc @friism :+1:

### CODE REVIEW

**Comment by tianon** [comment]
```diff
$ diff -u <(bashbrew cat hello-world) <(bashbrew cat <(./generate-stackbrew-library.sh))
--- /dev/fd/63	2017-09-12 15:04:54.592985049 -0700
+++ /dev/fd/62	2017-09-12 15:04:54.594984990 -0700
@@ -1,8 +1,9 @@
 Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon), Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
 GitRepo: https://github.com/docker-library/hello-world.git
-GitCommit: 7d0ee592e4ed60e2da9d59331e16ecdcadc1ed87
+GitCommit: e7ae2cf479db53d3110a0b5a609a32641a39467c
 
-Tags: latest
+Tags: linux
+SharedTags: latest
 Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
 amd64-Directory: amd64/hello-world
 amd64-GitCommit: 7d0ee592e4ed60e2da9d59331e16ecdcadc1ed87
@@ -20,6 +21,7 @@
 s390x-GitCommit: 7d0ee592e4ed60e2da9d59331e16ecdcadc1ed87
 
 Tags: nanoserver
+SharedTags: latest
 Architectures: windows-amd64
 windows-amd64-Directory: amd64/hello-world/nanoserver
 windows-amd64-GitCommit: 7d0ee592e4ed60e2da9d59331e16ecdcadc1ed87
```

**Comment by friism** [comment]
@tianon if for whatever reason (don't ask) I have a client that chokes on manifest list, what's the best fallback?

**Comment by tianon** [comment]
It's supposed to work such that you only get manifest lists if your client
explicitly requests them via Accept header, so I'd recommend adjusting said
client to not include that media type in the Accept header to the registry.
👍

**Comment by friism** [comment]
Thanks for not asking :-)

Current workaround is to use manifest tool to query for the right sha and the pull by digest

**Comment by friism** [comment]
Details here: https://github.com/moby/moby/pull/34829

**Comment by tianon** [comment]
Indeed, pull-by-digest should always work. 👍

https://github.com/docker-library/repo-info is a good resource for getting
digests too if one doesn't have manifest-tool handy (see the "remote"
subfolders under "repos").

**Pull request merged**
