### PR TITLE
Add "nanoserver" variants using "hello.txt" + powershell

### PR DESCRIPTION
**Pull request by tianon**
Closes #22
Closes #23

This implements the simpler txt-file-based method @yosifkit proposed in https://github.com/docker-library/hello-world/pull/23#issuecomment-261119434 for creating nanoserver variants. :+1:

### CODE REVIEW

**Comment by tianon** [comment]
```console
Docker@offcl-img-test MINGW64 ~/docker/hello-world ((3f49c5b...))
$ docker build hello-world/nanoserver
Sending build context to Docker daemon 3.584 kB
Step 1/3 : FROM microsoft/nanoserver
 ---> 787d9f9f8804
Step 2/3 : COPY hello.txt C:
 ---> 69b09b634328
Removing intermediate container 094565fb6465
Step 3/3 : CMD powershell -Command Get-Content C:\hello.txt
 ---> Running in c4c94d71997e
 ---> cabbfcafaf4c
Removing intermediate container c4c94d71997e
Successfully built cabbfcafaf4c

Docker@offcl-img-test MINGW64 ~/docker/hello-world ((3f49c5b...))
$ docker run --rm cabbfcafaf4c

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run a Nano Server container with:
 $ docker run -it microsoft/nanoserver powershell

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

```

**Comment by taylorb-microsoft** [comment]
I believe you could even simplify the nano example further with "type hello.txt" :).

**Comment by tianon** [comment]
@taylorb-microsoft heh, true -- although that's `cmd` and `powershell` is "The Future", right? :innocent:

**Comment by yosifkit** [comment]
This looks fine to me!

**Comment by taylorb-microsoft** [comment]
I'm all about using the smallest tool that fixes the job :)...  PowerShell still takes an extra few ms to start beyond CMD...

**Comment by friism** [comment]
haha, this is cheating :-)

**Comment by tianon** [comment]
@taylorb-microsoft yeah, fair -- I did some benchmarking to test:

- `CMD ["cmd", "/C", "type C:\\hello.txt"]`

```
real    0m5.321s
real    0m4.422s
real    0m4.858s
real    0m5.800s
```

- `CMD ["powershell", "-Command", "Get-Content C:\\hello.txt"]`

```
real    0m8.941s
real    0m8.867s
real    0m9.070s
real    0m8.565s
```

So, uh, that result is pretty clear.  I'm going to update this PR. :+1:

**Comment by tianon** [comment]
Updated!

**Comment by tianon** [comment]
@yosifkit made a good point in passing that helps rationalize this a little -- if we decided to make the Linux variants `FROM alpine`, we'd be using `cat` instead of a binary there too :smile:

**Comment by friism** [comment]
@tianon is there any hope of making this a multi-arch image with a fat manifest?

**Pull request merged**
